version: "3"

networks:
  ad-network:
    driver: bridge

services:
  backend-service:
    build:
      context: ./backend-api
      dockerfile: Dockerfile
    container_name: backend-container
    volumes:
      - ./backend-api:/var/www/html
      - ./webserver/php/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    depends_on:
      - ad_db_server
    networks:
      - ad-network

  webserver-nginx:
    image: nginx:stable-alpine
    container_name: webserver-nginx
    ports:
      - 9047:80
    volumes:
      - ./backend-api:/var/www/html:delegated
      - ./webserver/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend-service
    networks:
      - ad-network

  ad_db_server:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: ad_campaign
      MYSQL_USER: ad_user
      MYSQL_PASSWORD: 12345678
    container_name: ad_db_container
    ports:
      - "3330:3306"
    networks:
      - ad-network

  react-service:
    build:
      context: ./react-frontend
      dockerfile: Dockerfile
    container_name: react-container
    command: yarn start
    depends_on:
      - webserver-nginx
    ports:
      - "3007:3000"
    volumes:
      - ./react-frontend:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - ad-network
